CLASS LHC_SESSION DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR Session
        RESULT result,
      CALCULATESESSIONUUID FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  Session~CalculateSessionUUID .
ENDCLASS.

CLASS LHC_SESSION IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD CALCULATESESSIONUUID.
  ENDMETHOD.
ENDCLASS.
